// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthGitHubExchangeData, AuthGitHubExchangeErrors, AuthGitHubExchangeResponses, CheckoutData, CheckoutErrors, CheckoutResponses, DownloadAssetData, DownloadAssetErrors, DownloadAssetResponses, DownloadBundleData, DownloadBundleErrors, DownloadBundleResponses, GetAssetFileData, GetAssetFileErrors, GetAssetFileResponses, GetAssetManifestData, GetAssetManifestErrors, GetAssetManifestResponses, GetAssetReadmeData, GetAssetReadmeErrors, GetAssetReadmeResponses, GetBundleManifestData, GetBundleManifestErrors, GetBundleManifestResponses, GetBundleReadmeData, GetBundleReadmeErrors, GetBundleReadmeResponses, GetRegistryData, GetRegistryErrors, GetRegistryResponses, HealthData, HealthResponses, ListAssetFilesData, ListAssetFilesErrors, ListAssetFilesResponses, MeData, MeErrors, MeResponses, OpenApiData, OpenApiResponses, PublishData, PublishErrors, PublishPlanData, PublishPlanErrors, PublishPlanResponses, PublishResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Liveness probe
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>): RequestResult<HealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * This document
 */
export const openApi = <ThrowOnError extends boolean = false>(options?: Options<OpenApiData, ThrowOnError>): RequestResult<OpenApiResponses, unknown, ThrowOnError> => (options?.client ?? client).get<OpenApiResponses, unknown, ThrowOnError>({ url: '/openapi.json', ...options });

/**
 * Exchange a GitHub OAuth authorization code for an access token (web sign-in). GitHub's response body is returned verbatim.
 */
export const authGitHubExchange = <ThrowOnError extends boolean = false>(options: Options<AuthGitHubExchangeData, ThrowOnError>): RequestResult<AuthGitHubExchangeResponses, AuthGitHubExchangeErrors, ThrowOnError> => (options.client ?? client).post<AuthGitHubExchangeResponses, AuthGitHubExchangeErrors, ThrowOnError>({
    url: '/auth/github/exchange',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * The authenticated caller as resolved by the API
 */
export const me = <ThrowOnError extends boolean = false>(options?: Options<MeData, ThrowOnError>): RequestResult<MeResponses, MeErrors, ThrowOnError> => (options?.client ?? client).get<MeResponses, MeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me',
    ...options
});

/**
 * The registry index (`registry.json`) at the current commit. Supports `If-None-Match` with the `ETag` returned.
 */
export const getRegistry = <ThrowOnError extends boolean = false>(options?: Options<GetRegistryData, ThrowOnError>): RequestResult<GetRegistryResponses, GetRegistryErrors, ThrowOnError> => (options?.client ?? client).get<GetRegistryResponses, GetRegistryErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/registry',
    ...options
});

/**
 * The asset version's `manifest.json`
 */
export const getAssetManifest = <ThrowOnError extends boolean = false>(options: Options<GetAssetManifestData, ThrowOnError>): RequestResult<GetAssetManifestResponses, GetAssetManifestErrors, ThrowOnError> => (options.client ?? client).get<GetAssetManifestResponses, GetAssetManifestErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/assets/{type}/{name}/{version}/manifest',
    ...options
});

/**
 * The asset version's `README.md`
 */
export const getAssetReadme = <ThrowOnError extends boolean = false>(options: Options<GetAssetReadmeData, ThrowOnError>): RequestResult<GetAssetReadmeResponses, GetAssetReadmeErrors, ThrowOnError> => (options.client ?? client).get<GetAssetReadmeResponses, GetAssetReadmeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/assets/{type}/{name}/{version}/readme',
    ...options
});

/**
 * Every file in the asset version directory (manifest and README included)
 */
export const listAssetFiles = <ThrowOnError extends boolean = false>(options: Options<ListAssetFilesData, ThrowOnError>): RequestResult<ListAssetFilesResponses, ListAssetFilesErrors, ThrowOnError> => (options.client ?? client).get<ListAssetFilesResponses, ListAssetFilesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/assets/{type}/{name}/{version}/files',
    ...options
});

/**
 * Raw bytes of one file in the asset version directory (path from the `files` listing)
 */
export const getAssetFile = <ThrowOnError extends boolean = false>(options: Options<GetAssetFileData, ThrowOnError>): RequestResult<GetAssetFileResponses, GetAssetFileErrors, ThrowOnError> => (options.client ?? client).get<GetAssetFileResponses, GetAssetFileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/assets/{type}/{name}/{version}/file/{path}',
    ...options
});

/**
 * Zip of the asset and its transitive dependencies. Layout: `{name}/…` plus `dependencies/{dep}/…`. `format=skill` omits the top-level manifest and README and uses the `.skill` extension.
 */
export const downloadAsset = <ThrowOnError extends boolean = false>(options: Options<DownloadAssetData, ThrowOnError>): RequestResult<DownloadAssetResponses, DownloadAssetErrors, ThrowOnError> => (options.client ?? client).get<DownloadAssetResponses, DownloadAssetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/assets/{type}/{name}/{version}/download',
    ...options
});

/**
 * The bundle version's `bundle.json`
 */
export const getBundleManifest = <ThrowOnError extends boolean = false>(options: Options<GetBundleManifestData, ThrowOnError>): RequestResult<GetBundleManifestResponses, GetBundleManifestErrors, ThrowOnError> => (options.client ?? client).get<GetBundleManifestResponses, GetBundleManifestErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/bundles/{name}/{version}/manifest',
    ...options
});

/**
 * The bundle version's `README.md`
 */
export const getBundleReadme = <ThrowOnError extends boolean = false>(options: Options<GetBundleReadmeData, ThrowOnError>): RequestResult<GetBundleReadmeResponses, GetBundleReadmeErrors, ThrowOnError> => (options.client ?? client).get<GetBundleReadmeResponses, GetBundleReadmeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/bundles/{name}/{version}/readme',
    ...options
});

/**
 * Zip of the bundle: `bundle.json` at the root and each member under `{member}/…`. `format=skill` drops `bundle.json` and nests skill members as `{member}.skill`.
 */
export const downloadBundle = <ThrowOnError extends boolean = false>(options: Options<DownloadBundleData, ThrowOnError>): RequestResult<DownloadBundleResponses, DownloadBundleErrors, ThrowOnError> => (options.client ?? client).get<DownloadBundleResponses, DownloadBundleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/bundles/{name}/{version}/download',
    ...options
});

/**
 * Everything `atk checkout` needs in one call: the asset resolved by name, with every file base64 encoded.
 */
export const checkout = <ThrowOnError extends boolean = false>(options: Options<CheckoutData, ThrowOnError>): RequestResult<CheckoutResponses, CheckoutErrors, ThrowOnError> => (options.client ?? client).get<CheckoutResponses, CheckoutErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/checkout/{name}',
    ...options
});

/**
 * Validate a publish payload and return the plan (branch, path, PR title and body, files, reviewers, warnings) without touching GitHub.
 */
export const publishPlan = <ThrowOnError extends boolean = false>(options: Options<PublishPlanData, ThrowOnError>): RequestResult<PublishPlanResponses, PublishPlanErrors, ThrowOnError> => (options.client ?? client).post<PublishPlanResponses, PublishPlanErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/publish/plan',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Validate, then create the branch, commit and pull request on the registry with the caller's own token so the PR is authored by them. Global targets get the default reviewers; org targets use `reviewers`.
 */
export const publish = <ThrowOnError extends boolean = false>(options: Options<PublishData, ThrowOnError>): RequestResult<PublishResponses, PublishErrors, ThrowOnError> => (options.client ?? client).post<PublishResponses, PublishErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/publish',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
