// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://func-atk-prod.azurewebsites.net' | 'https://func-atk-dev.azurewebsites.net' | 'http://localhost:7071' | (string & {});
};

/**
 * Error envelope
 */
export type ApiError = {
    /**
     * Machine-readable error code
     */
    error: string;
    /**
     * Human-readable message
     */
    message: string;
    /**
     * Per-item problems for validation failures
     */
    details?: Array<ApiErrorDetail> | null;
};

/**
 * One problem
 */
export type ApiErrorDetail = {
    /**
     * What is wrong
     */
    message: string;
    /**
     * JSON pointer into the payload, when applicable
     */
    path?: string | null;
};

/**
 * One file with content
 */
export type CheckoutFile = {
    /**
     * Path relative to the version directory
     */
    path: string;
    /**
     * Always `base64`
     */
    encoding: string;
    /**
     * Base64 bytes
     */
    content: string;
    /**
     * Decoded size in bytes
     */
    size: number;
};

/**
 * A working copy of one asset version
 */
export type CheckoutResponse = {
    /**
     * Asset name
     */
    name: string;
    /**
     * Org scope
     */
    org?: string | null;
    /**
     * Asset type
     */
    type: 'skill' | 'agent' | 'rule' | 'hook' | 'memory-template' | 'mcp-config';
    /**
     * Resolved version
     */
    version: string;
    /**
     * Every file including manifest.json and README.md
     */
    files: Array<CheckoutFile>;
};

/**
 * A file in a version directory
 */
export type FileEntry = {
    /**
     * Path relative to the version directory
     */
    path: string;
    /**
     * Git blob sha
     */
    sha: string;
    /**
     * Size in bytes
     */
    size: number;
};

/**
 * Directory listing
 */
export type FileListResponse = {
    /**
     * Asset name
     */
    name: string;
    /**
     * Org scope
     */
    org?: string | null;
    /**
     * Asset type
     */
    type: 'skill' | 'agent' | 'rule' | 'hook' | 'memory-template' | 'mcp-config';
    /**
     * Resolved version
     */
    version: string;
    /**
     * Files, sorted by path
     */
    files: Array<FileEntry>;
};

/**
 * Liveness
 */
export type HealthResponse = {
    /**
     * Always `ok`
     */
    status: string;
    /**
     * Assembly version
     */
    version: string;
    /**
     * `Development` or `Production`
     */
    environment: string;
};

/**
 * OAuth code exchange
 */
export type OAuthExchangeRequest = {
    /**
     * Authorization code from the GitHub redirect
     */
    code: string;
};

/**
 * GitHub's token response, forwarded as-is
 */
export type OAuthTokenResponse = {
    /**
     * The user's GitHub token
     */
    access_token: string;
    /**
     * Granted scopes
     */
    scope?: string | null;
    /**
     * `bearer`
     */
    token_type?: string | null;
};

/**
 * The authenticated caller
 */
export type Principal = {
    /**
     * Auth scheme that validated the token (`github`)
     */
    scheme: string;
    /**
     * GitHub login
     */
    login: string;
    /**
     * Display name
     */
    name?: string | null;
    /**
     * Avatar URL
     */
    avatarUrl?: string | null;
};

/**
 * A file to commit
 */
export type PublishFile = {
    /**
     * Path relative to the version directory (no dotfiles, no `..`)
     */
    path: string;
    /**
     * File content, text or base64 per `encoding`
     */
    content: string;
    /**
     * Defaults to `utf8`
     */
    encoding?: 'utf8' | 'base64';
};

/**
 * What a publish would do
 */
export type PublishPlan = {
    /**
     * asset or bundle
     */
    kind: 'asset' | 'bundle';
    /**
     * Name
     */
    name: string;
    /**
     * Org scope
     */
    org?: string | null;
    /**
     * Asset type (assets only)
     */
    assetType?: 'skill' | 'agent' | 'rule' | 'hook' | 'memory-template' | 'mcp-config';
    /**
     * Version being published
     */
    version: string;
    /**
     * True when the registry already has this asset or bundle
     */
    isUpdate: boolean;
    /**
     * The registry's current latest when isUpdate
     */
    previousVersion?: string | null;
    /**
     * Branch that will be pushed
     */
    branchName: string;
    /**
     * Directory in the registry, with trailing slash
     */
    registryPath: string;
    /**
     * Pull request title
     */
    prTitle: string;
    /**
     * Pull request body (markdown)
     */
    prBody: string;
    /**
     * Files that will be committed, in order
     */
    files: Array<string>;
    /**
     * Reviewers that will be requested
     */
    reviewers: Array<string>;
    /**
     * Non-blocking advice (missing README, tags, unlisted files)
     */
    warnings: Array<string>;
};

/**
 * Publish payload
 */
export type PublishRequest = {
    /**
     * What is being published
     */
    kind: 'asset' | 'bundle';
    /**
     * The exact `manifest.json` (kind=asset) or `bundle.json` (kind=bundle) to commit. Validated against the registry's JSON Schema; `files` must be a concrete array.
     */
    manifest: {
        [key: string]: unknown;
    };
    /**
     * All other files: entrypoint, listed files, README.md. Bundles may only add README.md.
     */
    files?: Array<PublishFile> | null;
    /**
     * Optional notes appended to the PR body
     */
    message?: string | null;
    /**
     * Reviewers to request. Only allowed for org-scoped targets; global targets always get the default reviewers.
     */
    reviewers?: Array<string> | null;
    /**
     * Delete and recreate the publish branch if it already exists (the CLI's retry behaviour). Default false → 409 `branch_exists`.
     */
    replaceExistingBranch?: boolean;
    /**
     * Which client is publishing; only affects the PR footer
     */
    client?: 'cli' | 'web' | 'api';
};

/**
 * Result of a publish
 */
export type PublishResponse = {
    /**
     * Pull request URL
     */
    prUrl: string;
    /**
     * Pull request number
     */
    prNumber: number;
    /**
     * Branch pushed
     */
    branchName: string;
    /**
     * Commit created
     */
    commitSha: string;
    /**
     * Reviewers requested (the author is skipped)
     */
    reviewers: Array<string>;
    /**
     * Set when the reviewer request failed; the PR still exists
     */
    reviewerWarning?: string | null;
    /**
     * Non-blocking advice from validation
     */
    warnings: Array<string>;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Service is up
     */
    200: HealthResponse;
};

export type HealthResponse2 = HealthResponses[keyof HealthResponses];

export type OpenApiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.json';
};

export type OpenApiResponses = {
    /**
     * OpenAPI 3.1 document
     */
    200: {
        [key: string]: unknown;
    };
};

export type OpenApiResponse = OpenApiResponses[keyof OpenApiResponses];

export type AuthGitHubExchangeData = {
    body: OAuthExchangeRequest;
    path?: never;
    query?: never;
    url: '/auth/github/exchange';
};

export type AuthGitHubExchangeErrors = {
    /**
     * Missing code, or GitHub rejected it (`error` carries GitHub's OAuth error code)
     */
    400: ApiError;
    /**
     * OAuth app not configured
     */
    500: ApiError;
    /**
     * GitHub unreachable or returned an unusable response
     */
    502: ApiError;
};

export type AuthGitHubExchangeError = AuthGitHubExchangeErrors[keyof AuthGitHubExchangeErrors];

export type AuthGitHubExchangeResponses = {
    /**
     * GitHub token response
     */
    200: OAuthTokenResponse;
};

export type AuthGitHubExchangeResponse = AuthGitHubExchangeResponses[keyof AuthGitHubExchangeResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};

export type MeErrors = {
    /**
     * Missing or invalid token
     */
    401: ApiError;
    /**
     * Not an active EmergentSoftware member, or membership unverifiable (`not_org_member`, `org_membership_unverifiable`)
     */
    403: ApiError;
};

export type MeError = MeErrors[keyof MeErrors];

export type MeResponses = {
    /**
     * Principal
     */
    200: Principal;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type GetRegistryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/registry';
};

export type GetRegistryErrors = {
    /**
     * Missing or invalid token
     */
    401: ApiError;
    /**
     * Not an active EmergentSoftware member, or membership unverifiable (`not_org_member`, `org_membership_unverifiable`)
     */
    403: ApiError;
};

export type GetRegistryError = GetRegistryErrors[keyof GetRegistryErrors];

export type GetRegistryResponses = {
    /**
     * registry.json
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetRegistryResponse = GetRegistryResponses[keyof GetRegistryResponses];

export type GetAssetManifestData = {
    body?: never;
    path: {
        /**
         * Asset type
         */
        type: 'skill' | 'agent' | 'rule' | 'hook' | 'memory-template' | 'mcp-config';
        /**
         * Asset name (bare, no @org prefix)
         */
        name: string;
        /**
         * Exact semver version, or `latest`
         */
        version: string;
    };
    query?: {
        /**
         * Org scope (bare name, no `@`). Omit for global assets.
         */
        org?: string;
    };
    url: '/assets/{type}/{name}/{version}/manifest';
};

export type GetAssetManifestErrors = {
    /**
     * Missing or invalid token
     */
    401: ApiError;
    /**
     * Not an active EmergentSoftware member, or membership unverifiable (`not_org_member`, `org_membership_unverifiable`)
     */
    403: ApiError;
    /**
     * Unknown asset, version, or file
     */
    404: ApiError;
};

export type GetAssetManifestError = GetAssetManifestErrors[keyof GetAssetManifestErrors];

export type GetAssetManifestResponses = {
    /**
     * manifest.json
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetAssetManifestResponse = GetAssetManifestResponses[keyof GetAssetManifestResponses];

export type GetAssetReadmeData = {
    body?: never;
    path: {
        /**
         * Asset type
         */
        type: 'skill' | 'agent' | 'rule' | 'hook' | 'memory-template' | 'mcp-config';
        /**
         * Asset name (bare, no @org prefix)
         */
        name: string;
        /**
         * Exact semver version, or `latest`
         */
        version: string;
    };
    query?: {
        /**
         * Org scope (bare name, no `@`). Omit for global assets.
         */
        org?: string;
    };
    url: '/assets/{type}/{name}/{version}/readme';
};

export type GetAssetReadmeErrors = {
    /**
     * Missing or invalid token
     */
    401: ApiError;
    /**
     * Not an active EmergentSoftware member, or membership unverifiable (`not_org_member`, `org_membership_unverifiable`)
     */
    403: ApiError;
    /**
     * Unknown asset, version, or file
     */
    404: ApiError;
};

export type GetAssetReadmeError = GetAssetReadmeErrors[keyof GetAssetReadmeErrors];

export type GetAssetReadmeResponses = {
    /**
     * Markdown
     */
    200: string;
};

export type GetAssetReadmeResponse = GetAssetReadmeResponses[keyof GetAssetReadmeResponses];

export type ListAssetFilesData = {
    body?: never;
    path: {
        /**
         * Asset type
         */
        type: 'skill' | 'agent' | 'rule' | 'hook' | 'memory-template' | 'mcp-config';
        /**
         * Asset name (bare, no @org prefix)
         */
        name: string;
        /**
         * Exact semver version, or `latest`
         */
        version: string;
    };
    query?: {
        /**
         * Org scope (bare name, no `@`). Omit for global assets.
         */
        org?: string;
    };
    url: '/assets/{type}/{name}/{version}/files';
};

export type ListAssetFilesErrors = {
    /**
     * Missing or invalid token
     */
    401: ApiError;
    /**
     * Not an active EmergentSoftware member, or membership unverifiable (`not_org_member`, `org_membership_unverifiable`)
     */
    403: ApiError;
    /**
     * Unknown asset, version, or file
     */
    404: ApiError;
};

export type ListAssetFilesError = ListAssetFilesErrors[keyof ListAssetFilesErrors];

export type ListAssetFilesResponses = {
    /**
     * File list
     */
    200: FileListResponse;
};

export type ListAssetFilesResponse = ListAssetFilesResponses[keyof ListAssetFilesResponses];

export type GetAssetFileData = {
    body?: never;
    path: {
        /**
         * Asset type
         */
        type: 'skill' | 'agent' | 'rule' | 'hook' | 'memory-template' | 'mcp-config';
        /**
         * Asset name (bare, no @org prefix)
         */
        name: string;
        /**
         * Exact semver version, or `latest`
         */
        version: string;
        /**
         * File path relative to the version directory, e.g. `SKILL.md` or `reference/guide.md`
         */
        path: string;
    };
    query?: {
        /**
         * Org scope (bare name, no `@`). Omit for global assets.
         */
        org?: string;
    };
    url: '/assets/{type}/{name}/{version}/file/{path}';
};

export type GetAssetFileErrors = {
    /**
     * Missing or invalid token
     */
    401: ApiError;
    /**
     * Not an active EmergentSoftware member, or membership unverifiable (`not_org_member`, `org_membership_unverifiable`)
     */
    403: ApiError;
    /**
     * Unknown asset, version, or file
     */
    404: ApiError;
};

export type GetAssetFileError = GetAssetFileErrors[keyof GetAssetFileErrors];

export type GetAssetFileResponses = {
    /**
     * File content
     */
    200: Blob | File;
};

export type GetAssetFileResponse = GetAssetFileResponses[keyof GetAssetFileResponses];

export type DownloadAssetData = {
    body?: never;
    path: {
        /**
         * Asset type
         */
        type: 'skill' | 'agent' | 'rule' | 'hook' | 'memory-template' | 'mcp-config';
        /**
         * Asset name (bare, no @org prefix)
         */
        name: string;
        /**
         * Exact semver version, or `latest`
         */
        version: string;
    };
    query?: {
        /**
         * Org scope (bare name, no `@`). Omit for global assets.
         */
        org?: string;
        /**
         * Archive variant
         */
        format?: 'zip' | 'skill';
    };
    url: '/assets/{type}/{name}/{version}/download';
};

export type DownloadAssetErrors = {
    /**
     * Missing or invalid token
     */
    401: ApiError;
    /**
     * Not an active EmergentSoftware member, or membership unverifiable (`not_org_member`, `org_membership_unverifiable`)
     */
    403: ApiError;
    /**
     * Unknown asset, version, or file
     */
    404: ApiError;
};

export type DownloadAssetError = DownloadAssetErrors[keyof DownloadAssetErrors];

export type DownloadAssetResponses = {
    /**
     * Archive
     */
    200: Blob | File;
};

export type DownloadAssetResponse = DownloadAssetResponses[keyof DownloadAssetResponses];

export type GetBundleManifestData = {
    body?: never;
    path: {
        /**
         * Bundle name (bare, no @org prefix)
         */
        name: string;
        /**
         * Exact version, or `latest`
         */
        version: string;
    };
    query?: {
        /**
         * Org scope (bare name, no `@`). Omit for global assets.
         */
        org?: string;
    };
    url: '/bundles/{name}/{version}/manifest';
};

export type GetBundleManifestErrors = {
    /**
     * Missing or invalid token
     */
    401: ApiError;
    /**
     * Not an active EmergentSoftware member, or membership unverifiable (`not_org_member`, `org_membership_unverifiable`)
     */
    403: ApiError;
    /**
     * Unknown asset, version, or file
     */
    404: ApiError;
};

export type GetBundleManifestError = GetBundleManifestErrors[keyof GetBundleManifestErrors];

export type GetBundleManifestResponses = {
    /**
     * bundle.json
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetBundleManifestResponse = GetBundleManifestResponses[keyof GetBundleManifestResponses];

export type GetBundleReadmeData = {
    body?: never;
    path: {
        /**
         * Bundle name (bare, no @org prefix)
         */
        name: string;
        /**
         * Exact version, or `latest`
         */
        version: string;
    };
    query?: {
        /**
         * Org scope (bare name, no `@`). Omit for global assets.
         */
        org?: string;
    };
    url: '/bundles/{name}/{version}/readme';
};

export type GetBundleReadmeErrors = {
    /**
     * Missing or invalid token
     */
    401: ApiError;
    /**
     * Not an active EmergentSoftware member, or membership unverifiable (`not_org_member`, `org_membership_unverifiable`)
     */
    403: ApiError;
    /**
     * Unknown asset, version, or file
     */
    404: ApiError;
};

export type GetBundleReadmeError = GetBundleReadmeErrors[keyof GetBundleReadmeErrors];

export type GetBundleReadmeResponses = {
    /**
     * Markdown
     */
    200: string;
};

export type GetBundleReadmeResponse = GetBundleReadmeResponses[keyof GetBundleReadmeResponses];

export type DownloadBundleData = {
    body?: never;
    path: {
        /**
         * Bundle name (bare, no @org prefix)
         */
        name: string;
        /**
         * Exact version, or `latest`
         */
        version: string;
    };
    query?: {
        /**
         * Org scope (bare name, no `@`). Omit for global assets.
         */
        org?: string;
        /**
         * Archive variant
         */
        format?: 'zip' | 'skill';
    };
    url: '/bundles/{name}/{version}/download';
};

export type DownloadBundleErrors = {
    /**
     * Missing or invalid token
     */
    401: ApiError;
    /**
     * Not an active EmergentSoftware member, or membership unverifiable (`not_org_member`, `org_membership_unverifiable`)
     */
    403: ApiError;
    /**
     * Unknown asset, version, or file
     */
    404: ApiError;
};

export type DownloadBundleError = DownloadBundleErrors[keyof DownloadBundleErrors];

export type DownloadBundleResponses = {
    /**
     * Archive
     */
    200: Blob | File;
};

export type DownloadBundleResponse = DownloadBundleResponses[keyof DownloadBundleResponses];

export type CheckoutData = {
    body?: never;
    path: {
        /**
         * Asset name (bare)
         */
        name: string;
    };
    query?: {
        /**
         * Org scope (bare name, no `@`). Omit for global assets.
         */
        org?: string;
        /**
         * Asset type; required only when the name exists as more than one type
         */
        type?: 'skill' | 'agent' | 'rule' | 'hook' | 'memory-template' | 'mcp-config';
        /**
         * Exact version; defaults to `latest`
         */
        version?: string;
    };
    url: '/checkout/{name}';
};

export type CheckoutErrors = {
    /**
     * Ambiguous name (exists as several types) or bad type
     */
    400: ApiError;
    /**
     * Missing or invalid token
     */
    401: ApiError;
    /**
     * Not an active EmergentSoftware member, or membership unverifiable (`not_org_member`, `org_membership_unverifiable`)
     */
    403: ApiError;
    /**
     * Unknown asset, version, or file
     */
    404: ApiError;
};

export type CheckoutError = CheckoutErrors[keyof CheckoutErrors];

export type CheckoutResponses = {
    /**
     * Working copy
     */
    200: CheckoutResponse;
};

export type CheckoutResponse2 = CheckoutResponses[keyof CheckoutResponses];

export type PublishPlanData = {
    body: PublishRequest;
    path?: never;
    query?: never;
    url: '/publish/plan';
};

export type PublishPlanErrors = {
    /**
     * Payload failed schema or rule validation (`validation_failed`, `schema_invalid`, `invalid_reviewer`, `reviewers_not_allowed`)
     */
    400: ApiError;
    /**
     * Missing or invalid token
     */
    401: ApiError;
    /**
     * Not an active EmergentSoftware member, or membership unverifiable (`not_org_member`, `org_membership_unverifiable`)
     */
    403: ApiError;
    /**
     * `version_not_bumped`, `version_exists`, or `branch_exists`
     */
    409: ApiError;
};

export type PublishPlanError = PublishPlanErrors[keyof PublishPlanErrors];

export type PublishPlanResponses = {
    /**
     * Plan
     */
    200: PublishPlan;
};

export type PublishPlanResponse = PublishPlanResponses[keyof PublishPlanResponses];

export type PublishData = {
    body: PublishRequest;
    path?: never;
    query?: never;
    url: '/publish';
};

export type PublishErrors = {
    /**
     * Payload failed schema or rule validation (`validation_failed`, `schema_invalid`, `invalid_reviewer`, `reviewers_not_allowed`)
     */
    400: ApiError;
    /**
     * Missing or invalid token
     */
    401: ApiError;
    /**
     * Not an active EmergentSoftware member, or membership unverifiable (`not_org_member`, `org_membership_unverifiable`)
     */
    403: ApiError;
    /**
     * `version_not_bumped`, `version_exists`, or `branch_exists`
     */
    409: ApiError;
};

export type PublishError = PublishErrors[keyof PublishErrors];

export type PublishResponses = {
    /**
     * Pull request opened
     */
    201: PublishResponse;
};

export type PublishResponse2 = PublishResponses[keyof PublishResponses];
